// Copyright 2026 Kushan Shah
// SPDX-License-Identifier: Apache-2.0

// GeoStream Renderer Service — gRPC contract definition.
// This .proto file defines the API boundary between the Go orchestrator
// and the Python renderer microservice using binary Protocol Buffers.
//
// Generate code:
//   Go:     protoc --go_out=. --go-grpc_out=. proto/renderer.proto
//   Python: python -m grpc_tools.protoc -I. --python_out=services/renderer --grpc_python_out=services/renderer proto/renderer.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: renderer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WMSLayer represents a single WMS imagery layer to composite.
type WMSLayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Opacity       float64                `protobuf:"fixed64,3,opt,name=opacity,proto3" json:"opacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WMSLayer) Reset() {
	*x = WMSLayer{}
	mi := &file_renderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WMSLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WMSLayer) ProtoMessage() {}

func (x *WMSLayer) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WMSLayer.ProtoReflect.Descriptor instead.
func (*WMSLayer) Descriptor() ([]byte, []int) {
	return file_renderer_proto_rawDescGZIP(), []int{0}
}

func (x *WMSLayer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WMSLayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WMSLayer) GetOpacity() float64 {
	if x != nil {
		return x.Opacity
	}
	return 0
}

// RenderRequest contains all parameters needed to generate a geospatial video.
type RenderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Bbox           []float64              `protobuf:"fixed64,2,rep,packed,name=bbox,proto3" json:"bbox,omitempty"`                   // [minLng, minLat, maxLng, maxLat]
	StartDate      string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD
	EndDate        string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // YYYY-MM-DD
	Fps            int32                  `protobuf:"varint,5,opt,name=fps,proto3" json:"fps,omitempty"`
	FrameCount     int32                  `protobuf:"varint,6,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	Layers         []*WMSLayer            `protobuf:"bytes,7,rep,name=layers,proto3" json:"layers,omitempty"`
	TimeStep       string                 `protobuf:"bytes,8,opt,name=time_step,json=timeStep,proto3" json:"time_step,omitempty"`                   // e.g., "1d", "1h", "10m"
	TrackSatellite string                 `protobuf:"bytes,9,opt,name=track_satellite,json=trackSatellite,proto3" json:"track_satellite,omitempty"` // e.g., "ISS", "TERRA"
	OutputPath     string                 `protobuf:"bytes,10,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_renderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_renderer_proto_rawDescGZIP(), []int{1}
}

func (x *RenderRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RenderRequest) GetBbox() []float64 {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *RenderRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *RenderRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *RenderRequest) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *RenderRequest) GetFrameCount() int32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *RenderRequest) GetLayers() []*WMSLayer {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *RenderRequest) GetTimeStep() string {
	if x != nil {
		return x.TimeStep
	}
	return ""
}

func (x *RenderRequest) GetTrackSatellite() string {
	if x != nil {
		return x.TrackSatellite
	}
	return ""
}

func (x *RenderRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

// RenderResponse contains the rendering result.
type RenderResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "completed" or "failed"
	VideoPath       string                 `protobuf:"bytes,2,opt,name=video_path,json=videoPath,proto3" json:"video_path,omitempty"`
	Metrics         []float64              `protobuf:"fixed64,3,rep,packed,name=metrics,proto3" json:"metrics,omitempty"`                                 // Per-frame activity percentages
	DurationSeconds float64                `protobuf:"fixed64,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // Wall-clock render time
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_renderer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_renderer_proto_rawDescGZIP(), []int{2}
}

func (x *RenderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RenderResponse) GetVideoPath() string {
	if x != nil {
		return x.VideoPath
	}
	return ""
}

func (x *RenderResponse) GetMetrics() []float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *RenderResponse) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_renderer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_renderer_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CacheType     string                 `protobuf:"bytes,2,opt,name=cache_type,json=cacheType,proto3" json:"cache_type,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_renderer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_renderer_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetCacheType() string {
	if x != nil {
		return x.CacheType
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_renderer_proto protoreflect.FileDescriptor

const file_renderer_proto_rawDesc = "" +
	"\n" +
	"\x0erenderer.proto\x12\brenderer\"J\n" +
	"\bWMSLayer\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aopacity\x18\x03 \x01(\x01R\aopacity\"\xba\x02\n" +
	"\rRenderRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04bbox\x18\x02 \x03(\x01R\x04bbox\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x10\n" +
	"\x03fps\x18\x05 \x01(\x05R\x03fps\x12\x1f\n" +
	"\vframe_count\x18\x06 \x01(\x05R\n" +
	"frameCount\x12*\n" +
	"\x06layers\x18\a \x03(\v2\x12.renderer.WMSLayerR\x06layers\x12\x1b\n" +
	"\ttime_step\x18\b \x01(\tR\btimeStep\x12'\n" +
	"\x0ftrack_satellite\x18\t \x01(\tR\x0etrackSatellite\x12\x1f\n" +
	"\voutput_path\x18\n" +
	" \x01(\tR\n" +
	"outputPath\"\x8c\x01\n" +
	"\x0eRenderResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"video_path\x18\x02 \x01(\tR\tvideoPath\x12\x18\n" +
	"\ametrics\x18\x03 \x03(\x01R\ametrics\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x01R\x0fdurationSeconds\"\x0f\n" +
	"\rHealthRequest\"a\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"cache_type\x18\x02 \x01(\tR\tcacheType\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\x95\x01\n" +
	"\x0fRendererService\x12@\n" +
	"\vRenderVideo\x12\x17.renderer.RenderRequest\x1a\x18.renderer.RenderResponse\x12@\n" +
	"\vHealthCheck\x12\x17.renderer.HealthRequest\x1a\x18.renderer.HealthResponseB\x8c\x01\n" +
	"\fcom.rendererB\rRendererProtoP\x01Z-github.com/kushanj/geo-backend/internal/proto\xa2\x02\x03RXX\xaa\x02\bRenderer\xca\x02\bRenderer\xe2\x02\x14Renderer\\GPBMetadata\xea\x02\bRendererb\x06proto3"

var (
	file_renderer_proto_rawDescOnce sync.Once
	file_renderer_proto_rawDescData []byte
)

func file_renderer_proto_rawDescGZIP() []byte {
	file_renderer_proto_rawDescOnce.Do(func() {
		file_renderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_renderer_proto_rawDesc), len(file_renderer_proto_rawDesc)))
	})
	return file_renderer_proto_rawDescData
}

var file_renderer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_renderer_proto_goTypes = []any{
	(*WMSLayer)(nil),       // 0: renderer.WMSLayer
	(*RenderRequest)(nil),  // 1: renderer.RenderRequest
	(*RenderResponse)(nil), // 2: renderer.RenderResponse
	(*HealthRequest)(nil),  // 3: renderer.HealthRequest
	(*HealthResponse)(nil), // 4: renderer.HealthResponse
}
var file_renderer_proto_depIdxs = []int32{
	0, // 0: renderer.RenderRequest.layers:type_name -> renderer.WMSLayer
	1, // 1: renderer.RendererService.RenderVideo:input_type -> renderer.RenderRequest
	3, // 2: renderer.RendererService.HealthCheck:input_type -> renderer.HealthRequest
	2, // 3: renderer.RendererService.RenderVideo:output_type -> renderer.RenderResponse
	4, // 4: renderer.RendererService.HealthCheck:output_type -> renderer.HealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_renderer_proto_init() }
func file_renderer_proto_init() {
	if File_renderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_renderer_proto_rawDesc), len(file_renderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_renderer_proto_goTypes,
		DependencyIndexes: file_renderer_proto_depIdxs,
		MessageInfos:      file_renderer_proto_msgTypes,
	}.Build()
	File_renderer_proto = out.File
	file_renderer_proto_goTypes = nil
	file_renderer_proto_depIdxs = nil
}
