// Copyright 2026 Kushan Shah
// SPDX-License-Identifier: Apache-2.0

// GeoStream Renderer Service — gRPC contract definition.
// This .proto file defines the API boundary between the Go orchestrator
// and the Python renderer microservice using binary Protocol Buffers.
//
// Generate code:
//   Go:     protoc --go_out=. --go-grpc_out=. proto/renderer.proto
//   Python: python -m grpc_tools.protoc -I. --python_out=services/renderer --grpc_python_out=services/renderer proto/renderer.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: renderer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RendererService_RenderVideo_FullMethodName = "/renderer.RendererService/RenderVideo"
	RendererService_HealthCheck_FullMethodName = "/renderer.RendererService/HealthCheck"
)

// RendererServiceClient is the client API for RendererService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RendererService handles video rendering requests from the Go orchestrator.
type RendererServiceClient interface {
	// RenderVideo accepts rendering parameters and returns the generated video path.
	RenderVideo(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
	// HealthCheck verifies the renderer service is operational.
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type rendererServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRendererServiceClient(cc grpc.ClientConnInterface) RendererServiceClient {
	return &rendererServiceClient{cc}
}

func (c *rendererServiceClient) RenderVideo(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, RendererService_RenderVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rendererServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RendererService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RendererServiceServer is the server API for RendererService service.
// All implementations must embed UnimplementedRendererServiceServer
// for forward compatibility.
//
// RendererService handles video rendering requests from the Go orchestrator.
type RendererServiceServer interface {
	// RenderVideo accepts rendering parameters and returns the generated video path.
	RenderVideo(context.Context, *RenderRequest) (*RenderResponse, error)
	// HealthCheck verifies the renderer service is operational.
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedRendererServiceServer()
}

// UnimplementedRendererServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRendererServiceServer struct{}

func (UnimplementedRendererServiceServer) RenderVideo(context.Context, *RenderRequest) (*RenderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderVideo not implemented")
}
func (UnimplementedRendererServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRendererServiceServer) mustEmbedUnimplementedRendererServiceServer() {}
func (UnimplementedRendererServiceServer) testEmbeddedByValue()                         {}

// UnsafeRendererServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RendererServiceServer will
// result in compilation errors.
type UnsafeRendererServiceServer interface {
	mustEmbedUnimplementedRendererServiceServer()
}

func RegisterRendererServiceServer(s grpc.ServiceRegistrar, srv RendererServiceServer) {
	// If the following call panics, it indicates UnimplementedRendererServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RendererService_ServiceDesc, srv)
}

func _RendererService_RenderVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendererServiceServer).RenderVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RendererService_RenderVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendererServiceServer).RenderVideo(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RendererService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendererServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RendererService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendererServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RendererService_ServiceDesc is the grpc.ServiceDesc for RendererService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RendererService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "renderer.RendererService",
	HandlerType: (*RendererServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenderVideo",
			Handler:    _RendererService_RenderVideo_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _RendererService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "renderer.proto",
}
