# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: renderer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'renderer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erenderer.proto\x12\x08renderer\"6\n\x08WMSLayer\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07opacity\x18\x03 \x01(\x01\"\xda\x01\n\rRenderRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0c\n\x04\x62\x62ox\x18\x02 \x03(\x01\x12\x12\n\nstart_date\x18\x03 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x04 \x01(\t\x12\x0b\n\x03\x66ps\x18\x05 \x01(\x05\x12\x13\n\x0b\x66rame_count\x18\x06 \x01(\x05\x12\"\n\x06layers\x18\x07 \x03(\x0b\x32\x12.renderer.WMSLayer\x12\x11\n\ttime_step\x18\x08 \x01(\t\x12\x17\n\x0ftrack_satellite\x18\t \x01(\t\x12\x13\n\x0boutput_path\x18\n \x01(\t\"_\n\x0eRenderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nvideo_path\x18\x02 \x01(\t\x12\x0f\n\x07metrics\x18\x03 \x03(\x01\x12\x18\n\x10\x64uration_seconds\x18\x04 \x01(\x01\"\x0f\n\rHealthRequest\"E\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\ncache_type\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t2\x95\x01\n\x0fRendererService\x12@\n\x0bRenderVideo\x12\x17.renderer.RenderRequest\x1a\x18.renderer.RenderResponse\x12@\n\x0bHealthCheck\x12\x17.renderer.HealthRequest\x1a\x18.renderer.HealthResponseB8Z6github.com/kushanj/geo-backend/internal/proto/rendererb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'renderer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/kushanj/geo-backend/internal/proto/renderer'
  _globals['_WMSLAYER']._serialized_start=28
  _globals['_WMSLAYER']._serialized_end=82
  _globals['_RENDERREQUEST']._serialized_start=85
  _globals['_RENDERREQUEST']._serialized_end=303
  _globals['_RENDERRESPONSE']._serialized_start=305
  _globals['_RENDERRESPONSE']._serialized_end=400
  _globals['_HEALTHREQUEST']._serialized_start=402
  _globals['_HEALTHREQUEST']._serialized_end=417
  _globals['_HEALTHRESPONSE']._serialized_start=419
  _globals['_HEALTHRESPONSE']._serialized_end=488
  _globals['_RENDERERSERVICE']._serialized_start=491
  _globals['_RENDERERSERVICE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
