# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import renderer_pb2 as renderer__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in renderer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RendererServiceStub(object):
    """RendererService handles video rendering requests from the Go orchestrator.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RenderVideo = channel.unary_unary(
                '/renderer.RendererService/RenderVideo',
                request_serializer=renderer__pb2.RenderRequest.SerializeToString,
                response_deserializer=renderer__pb2.RenderResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/renderer.RendererService/HealthCheck',
                request_serializer=renderer__pb2.HealthRequest.SerializeToString,
                response_deserializer=renderer__pb2.HealthResponse.FromString,
                _registered_method=True)


class RendererServiceServicer(object):
    """RendererService handles video rendering requests from the Go orchestrator.
    """

    def RenderVideo(self, request, context):
        """RenderVideo accepts rendering parameters and returns the generated video path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck verifies the renderer service is operational.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RendererServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RenderVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderVideo,
                    request_deserializer=renderer__pb2.RenderRequest.FromString,
                    response_serializer=renderer__pb2.RenderResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=renderer__pb2.HealthRequest.FromString,
                    response_serializer=renderer__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'renderer.RendererService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('renderer.RendererService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RendererService(object):
    """RendererService handles video rendering requests from the Go orchestrator.
    """

    @staticmethod
    def RenderVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/renderer.RendererService/RenderVideo',
            renderer__pb2.RenderRequest.SerializeToString,
            renderer__pb2.RenderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/renderer.RendererService/HealthCheck',
            renderer__pb2.HealthRequest.SerializeToString,
            renderer__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
